epochs:
  desc: Number of epochs to train over
  value: 20
batch_size:
  desc: Size of each mini-batch
  value: 8
 Modle_name:
  desc: which model is being run
  value: Adult-specific model
 LR_start rate:
  desc: We use LR decay that starts with this value
  value:0.01
