epochs:
  desc: Number of epochs to train over
  value: 20
batch_size:
  desc: Size of each mini-batch
  value: 32
lr:
  desc: We use LR decay that starts with this value
  value: 0.01
patience:
  desc: Patience for scheduler
  value: 100
age:
  desc: adult or kids
  value: 'adults'
