epochs:
  desc: Number of epochs to train over
  value: 100
batch_size:
  desc: Size of each mini-batch
  value: 32
 Modle_name:
  desc: which model is being run
  value: Kid-specific model
 LR_start rate:
  desc: We use LR decay that starts with this value
  value:
